apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: demo-stand
  namespace: demo
spec:
  affinity:
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys:
    - kubernetes.io/hostname
  clusterDefinitionRef: apecloud-mysql
  clusterVersionRef: ac-mysql-8.0.30
  componentSpecs:
    - componentDefRef: mysql
      monitor: false
      name: mysql
      replicas: 3
      resources:
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: alicloud-disk-essd 
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
  terminationPolicy: Delete