apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: demo-raft
  namespace: demo
  labels: 
    app.kubernetes.io/version: "8.0.33"
    app.kubernetes.io/instance: mysql
spec:
  clusterVersionRef: mysql-8.0.33
  terminationPolicy: Delete
  affinity:
    podAntiAffinity: Preferred
    topologyKeys:
    - kubernetes.io/hostname
    tenancy: SharedNode
  clusterDefinitionRef: mysql
  componentSpecs:
    - name: mysql
      componentDefRef: mysql
      monitor: false 
      replicas: 3
      resources:
        limits:
          cpu: "0.5"
          memory: "2Gi"
        requests:
          cpu: "0.2"
          memory: "0.5Gi"
      volumeClaimTemplates:
        - name: data # ref clusterDefinition components.containers.volumeMounts.name
          spec:
            storageClassName: alicloud-disk-essd
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi