---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-budibase-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi