---
apiVersion: v1
kind: Service
metadata:
  name: budibase-service
  labels:
    app.kubernetes.io/name: budibase
spec:
  selector:
    app.kubernetes.io/name: budibase
  type: ClusterIP
  # type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: web
      # nodePort: 30080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budibase-ingress
  labels:
    app.kubernetes.io/name: budibase
spec:
  ingressClassName: nginx
  rules:
    - host: "budibase.k8s.local"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: budibase-service
                port:
                  number: 80
  tls:
    - hosts: 
      - budibase.k8s.local
      secretName: budibase-ca