version: "3.8"
services:
  db:
    container_name: db
    image: registry.cn-guangzhou.aliyuncs.com/kubernetes-default/mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456